version: "3.8"
services:
  api:
    build:
      context: ./apps/api
    container_name: autotrack_api
    ports:
      - "8000:8000"
    volumes:
      - ./apps/api:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/autotrack

  db:
    image: postgres:15
    container_name: autotrack_db
    environment:
      POSTGRES_DB: autotrack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: autotrack_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  minio:
    image: minio/minio
    container_name: autotrack_minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data

volumes:
  pgdata:
  minio_data:
